### ISSUE TITLE
Crashing when changing from Single monitor mode to extended

### ISSUE THREAD

**Issue by joengs** [FancyWM/fancywm-issues#66] opened 2022-03-03 19:15 UTC
**Describe the bug**
Changing monitor mode to extended mode  on my laptop causes the FancyVM to crash. 

**To Reproduce**
1. Connect a monitor in extended mode
2. Open FancyWM so that all widows are side by side
3. Click on Win+P and change the display mode to Primary Only
4. Change mode to Extended again by pressing Win + P and set it to extended
5. FancyWM will crash and an error message will be shown.

**Expected behavior**
It should automatically populate the extended monitor and the primary monitor the way it was before, or similar

**Screenshots**
![image](https://user-images.githubusercontent.com/31697578/156635839-ab36d131-8c67-4bb2-b5ff-023afaf39c53.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Build 19042

**Comment by veselink1** [comment] 2022-03-03 20:50
Thanks for reporting. This is a duplicate of #64.

**Closed by veselink1** 2022-03-03 20:50 UTC
