### ISSUE TITLE
Low Priority: FancyWM settings responsivity / narrow-width text cutoff

### ISSUE THREAD

**Issue by rayat-amperity** [FancyWM/fancywm-issues#22] opened 2021-12-31 21:36 UTC
**Describe the bug**

> Apologies for assuming priority on your behalf, but didn't want to stress you out when you saw this in your inbox. Feel free to remove prefix in title.

The settings app, in particular the (Floating windows) Rules page, will cut off text content contained in the individual setting cards, if the window is set to certain (narrow) widths. Example screenshot attached.

**To Reproduce**
1. Open FancyWM settings app.
2. Navigate to Rules page
3. Resize window to a width like in the screenshot
4. See text cut off with no means by which to read the rest of the text.

**Expected behavior**

One or all of the following:

1. Horizontal scroll bar either app/page level, or card-level
2. Responsivity ( eg have the card increase in height in response to text overflow )
3. Toggleable sidebar ( eg it collapses to a icon-only menu with tooltips, a hamburger menu button and/or a pin-collapse button )

**Screenshots**
![image](https://user-images.githubusercontent.com/93224139/147839232-d5434f14-ecc5-441c-8a39-179b23aaef0a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 19044.1415 64 bit

**Comment by veselink1** [comment] 2022-01-11 17:13
Ah, I see what the problem is, thanks for reporting.

**Comment by veselink1** [comment] 2022-01-23 13:45
Should be fixed in v2.4.0 available now. Thanks for reporting!

**Closed** 2022-01-31 21:50 UTC
Labels: bug
