### ISSUE TITLE
Crashes 15 seconds after startup, seemingly unable to check license status

### ISSUE THREAD

**Issue by m-dango** [FancyWM/fancywm-issues#30] opened 2022-01-26 11:24 UTC
**Describe the bug**
FancyWM crashes roughly 15 seconds after it starts every time. Looking at the License Status page in Settings, it never gets beyond the `Checking...` status.

Additionally, this crash has only been recurring repeatedly starting today. Had previous occasional crashes but never regular. I've made no notable changes that I would suspect would have introduced this behaviour.

Throws: `Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The data is invalid.`

```
Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: The data is invalid.
   at System.Security.Cryptography.ProtectedData.ProtectOrUnprotect(Byte[] inputData, Byte[] optionalEntropy, DataProtectionScope scope, Boolean protect)
   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at FancyWM.Analytics.LicenseManager.GetUtcTimeOfLastCheckAsync()
   at FancyWM.MainWindow.DoLicenseCheck()
   at FancyWM.MainWindow.OnLoaded(Object sender, RoutedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__127_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at FancyWM.Startup.Main(String[] args)
```

**Desktop**
 - OS: Windows 10
 - Version: 21H2

**Comment by m-dango** [comment] 2022-01-26 11:32
Uninstalling and reinstalling the app appears to have resolved the issue.

**Comment by veselink1** [comment] 2022-01-31 22:10
Thanks for reporting this.
This is most likely caused by the local license file being corrupt.  
I am closing the issue since it is (thus far) the only reported occurence.

**Closed by veselink1** 2022-01-31 22:10 UTC
Labels: bug

**Comment by gwrx** [comment] 2022-03-17 09:11
Same issue here.
Corrupt or missing licence file may cause the isse since it stopped working after migrating my local user profile to a domain user profile. So it might be an idea to look into the issue why FancyWM can't get the licence state from the Microsoft Store...

**Comment by blaberry** [comment] 2022-04-25 11:34
+1 on this, it took quite some time to find this issue since it's closed. Maybe it could be open to make it easier to search for until a fix is in place?

For me reauthenticating to the microsoft store did nothing, but uninstalling and reinstalling seems to have resolved the issue for now.

**Comment by Juxsta** [comment] 2022-09-21 05:53
+1 for me as well
