### ISSUE TITLE
Keybind to move entire panels

### ISSUE THREAD

**Issue by vbarrancos** [FancyWM/fancywm-issues#116] opened 2022-07-23 07:18 UTC
**Is your feature request related to a problem? Please describe.**
I prefer to avoid using the mouse for any sort of window management if at all possible.  Currently FancyWM lets me do this for almost everything, but I occasionally run into situations where I want to move an entire panel rather than just the individual windows inside of it for which there doesn't appear to be an elegant keyboard-only solution.

Currently I have to either using the mouse to drag the panel's bar over to its new location, or just do a ton of keyboard operations to promote windows out of the panel in the old location to get rid of it, then move them into a new panel at the desired location.

**Describe the solution you'd like**
I'd really appreciate keybinds to move the entire panel owning the currently focused window in a given direction.

**Describe alternatives you've considered**
This almost always happens when I'm trying to set up my "usual" panel configuration for a particular monitor/desktop, so alternatively a way to save/load panel configurations would probably obviate the need for more keybinds, but I imagine that would be a lot more work.

Thanks, FancyWM is a nifty piece of software.

**Comment by veselink1** [comment] 2022-08-07 15:49
Thanks for the feature request.

**Comment by sim590** [comment] 2022-08-15 15:29
this is the exact same request as #97.

**Comment by sim590** [comment] 2022-08-15 15:30
May be this issue should be closed in favor of #97.

**Comment by veselink1** [comment] 2022-08-15 21:04
Thanks for the feature request. Closed as duplicate of #97.

**Closed by veselink1** 2022-08-15 21:04 UTC
Labels: feature
